baseURL = "https://example.com/"
title = "SL Notebook"

[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'


# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
themeVariant='oe'
disableLandingPageButton = true
collapsibleMenu = true
alwaysopen = true

