baseURL = "https://example.com/"
title = "SL Notebook"
#enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
#theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
#theme = "compose"
#enableGitInfo = true

#disableKinds = ["taxonomy", "taxonomyTerm"]

#[outputs]
#  home = ["HTML", "RSS","JSON"]

[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'


# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
themeVariant='oe'
disableLandingPageButton = true
collapsibleMenu = true
alwaysopen = true

