baseURL = "https://juan-castrillon.github.io/sl-notes-v2"
title = "SL Notebook"

[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'


# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
themeVariant='oe'
disableLandingPageButton = true
disableInlineCopyToClipBoard = true
collapsibleMenu = true
alwaysopen = true

[markup]
  [markup.highlight]
    guessSyntax = false
    style = "github-dark"
